import type { Metadata } from "next";

const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://peer-review.dev";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "PeerReview terms of service — acceptable use, intellectual property, and liability.",
    alternates: { canonical: `${baseUrl}/terms` },
    robots: { index: true, follow: true },
};

export default function TermsPage() {
    return (
        <div className="max-w-3xl mx-auto px-6 py-16 prose prose-invert prose-sm">
            <h1>Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: March 8, 2026</p>

            <h2>1. Acceptance of Terms</h2>
            <p>
                By accessing or using PeerReview (&quot;the Service&quot;), you agree to be bound by these Terms
                of Service. If you do not agree to these terms, you may not use the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
                PeerReview is a web-based platform that provides code review practice exercises with
                AI-powered feedback. Users can browse pull request exercises, leave inline comments,
                and receive automated feedback on their review quality.
            </p>

            <h2>3. Account Registration</h2>
            <p>
                You must create an account to use certain features of the Service. You are responsible
                for maintaining the confidentiality of your account credentials and for all activities
                that occur under your account.
            </p>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Submit malicious code or content through review comments</li>
                <li>Abuse the AI feedback system through automated or excessive requests</li>
                <li>Harass, abuse, or harm other users through discussions or solutions</li>
                <li>Scrape, crawl, or otherwise extract data from the Service without permission</li>
            </ul>

            <h2>5. Subscriptions and Payments</h2>
            <p>
                PeerReview offers free and paid subscription tiers. Paid subscriptions are billed
                monthly through Stripe. You may cancel your subscription at any time through your
                account settings. Refunds are handled on a case-by-case basis.
            </p>

            <h2>6. Intellectual Property</h2>
            <p>
                The code review exercises on PeerReview are provided for educational purposes.
                Your review comments and submitted solutions remain your intellectual property.
                You grant PeerReview a non-exclusive license to display your community contributions
                (discussions, solutions) on the platform.
            </p>

            <h2>7. AI-Generated Content</h2>
            <p>
                AI feedback provided by the Service is generated by third-party AI models and is
                intended for educational purposes only. PeerReview does not guarantee the accuracy
                or completeness of AI-generated feedback.
            </p>

            <h2>8. Limitation of Liability</h2>
            <p>
                PeerReview is provided &quot;as is&quot; without warranties of any kind. We are not liable
                for any indirect, incidental, or consequential damages arising from your use of the
                Service. Our total liability shall not exceed the amount you paid for the Service
                in the 12 months preceding the claim.
            </p>

            <h2>9. Termination</h2>
            <p>
                We reserve the right to suspend or terminate your account if you violate these terms.
                You may delete your account at any time. Upon termination, your right to use the
                Service ceases immediately.
            </p>

            <h2>10. Changes to Terms</h2>
            <p>
                We may modify these terms at any time. Continued use of the Service after changes
                constitutes acceptance of the modified terms. We will notify users of material
                changes via email or in-app notification.
            </p>

            <h2>11. Governing Law</h2>
            <p>
                These terms are governed by and construed in accordance with the laws of France.
                Any disputes shall be resolved in the courts of France.
            </p>
        </div>
    );
}
